services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: micro-golubator.rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: micro-golubator.app
    ports:
      - "8000:8000"
    environment:
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASS}
    volumes:
      - ./app:/app
    depends_on:
      rabbitmq:
        condition: service_healthy


  bot:
    build:
      context: ./bot
      dockerfile: ./Dockerfile
    container_name: micro-golubator.bot
    environment:
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASS: ${RABBIT_PASS}
      BOT_TOKEN: ${BOT_TOKEN}
    volumes:
      - ./bot:/app
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq_data:
